In [1]:
import pandas as pd

df = pd.read_csv('data/sonar.csv', header=None)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [2]:
print(df.head())

       0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   

In [3]:
print(df.tail())

         0       1       2       3       4       5       6       7       8   \
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
203  0.0193  0.0157   M  
204  0.0062  0.0

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

In [7]:
import numpy as np
import tensorflow as tf

In [9]:
# seed 값 설정
np.random.seed(3)
tf.random.set_seed(3)

In [15]:
# 데이터 입력
dataset = df.values
X= dataset[:,0:60].astype(float)
y_obj = dataset[:,60]
print(X)

[[0.02   0.0371 0.0428 ... 0.0084 0.009  0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]


In [16]:
# 문자열 반환
e = LabelEncoder()
e.fit(y_obj)
y= e.transform(y_obj)

In [17]:
# 모델 설정
model = Sequential()
model.add(Dense(24, input_dim=60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [18]:
# 모델 컴파일 및 훈련
model.compile(loss='mean_squared_error', \
             optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, batch_size=5)

Epoch 1/200
42/42 [==============================] - 0s 1ms/step - loss: 0.2518 - accuracy: 0.4760
Epoch 2/200
42/42 [==============================] - 0s 1ms/step - loss: 0.2444 - accuracy: 0.5529
Epoch 3/200
42/42 [==============================] - 0s 905us/step - loss: 0.2352 - accuracy: 0.6538
Epoch 4/200
42/42 [==============================] - 0s 738us/step - loss: 0.2160 - accuracy: 0.7356
Epoch 5/200
42/42 [==============================] - 0s 738us/step - loss: 0.1903 - accuracy: 0.7452
Epoch 6/200
42/42 [==============================] - 0s 762us/step - loss: 0.1752 - accuracy: 0.7692
Epoch 7/200
42/42 [==============================] - 0s 714us/step - loss: 0.1588 - accuracy: 0.7933
Epoch 8/200
42/42 [==============================] - 0s 833us/step - loss: 0.1506 - accuracy: 0.7933
Epoch 9/200
42/42 [==============================] - 0s 834us/step - loss: 0.1484 - accuracy: 0.8077
Epoch 10/200
42/42 [==============================] - 0s 738us/step - loss: 0.1418 - accuracy: 

42/42 [==============================] - 0s 595us/step - loss: 0.0071 - accuracy: 0.9952
Epoch 161/200
42/42 [==============================] - 0s 619us/step - loss: 0.0068 - accuracy: 0.9952
Epoch 162/200
42/42 [==============================] - 0s 595us/step - loss: 0.0069 - accuracy: 0.9952
Epoch 163/200
42/42 [==============================] - 0s 595us/step - loss: 0.0084 - accuracy: 0.9952
Epoch 164/200
42/42 [==============================] - 0s 619us/step - loss: 0.0075 - accuracy: 0.9952
Epoch 165/200
42/42 [==============================] - 0s 619us/step - loss: 0.0068 - accuracy: 0.9952
Epoch 166/200
42/42 [==============================] - 0s 643us/step - loss: 0.0067 - accuracy: 0.9952
Epoch 167/200
42/42 [==============================] - 0s 738us/step - loss: 0.0060 - accuracy: 0.9952
Epoch 168/200
42/42 [==============================] - 0s 690us/step - loss: 0.0077 - accuracy: 0.9952
Epoch 169/200
42/42 [==============================] - 0s 690us/step - loss: 0.0065 - a

In [19]:
#1464 250 11
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 24)                1464      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                250       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 11        
Total params: 1,725
Trainable params: 1,725
Non-trainable params: 0
_________________________________________________________________
