In [1]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [2]:
text='해보지 않으면 해낼 수 없다'
result=text_to_word_sequence(text)
print('원문:', text)
print('토큰화:',result)

원문: 해보지 않으면 해낼 수 없다
토큰화: ['해보지', '않으면', '해낼', '수', '없다']


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.', '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.', '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',]

In [5]:
token=Tokenizer() #토큰화 함수 지정
token.fit_on_texts(docs) #토큰화 함수에 문자 적용

In [6]:
print('단어 카운트:', token.word_counts)

단어 카운트: OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [7]:
print('문장 카운트:', token.document_count)

문장 카운트: 3


In [8]:
print('각 단어가 몇개의 문장에 포함되어 있는가?:', token.word_docs)

각 단어가 몇개의 문장에 포함되어 있는가?: defaultdict(<class 'int'>, {'먼저': 1, '토큰화합니다': 1, '나누어': 1, '각': 1, '단어를': 1, '텍스트의': 2, '토큰화해야': 1, '딥러닝에서': 2, '인식됩니다': 1, '단어로': 1, '사용할': 1, '토큰화한': 1, '있습니다': 1, '수': 1, '결과는': 1})


In [9]:
print('각 단어에 매겨진 인덱스 값:',token.word_index)

각 단어에 매겨진 인덱스 값: {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [10]:
text='오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token=Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [11]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [12]:
from tensorflow.keras.utils import to_categorical

word_size=len(token.word_index)+1
x=to_categorical(x,num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [13]:
docs=['너무 재밌네요','최고에요','참 잘 만든 영화에요', '추천하고 싶은 영화입니다.','한 번 더 보고싶네요', '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색하네요', '재미없어요']

In [14]:
import numpy as np
classes=np.array([1,1,1,1,1,0,0,0,0,0])

In [15]:
token=Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로에요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색하네요': 20, '재미없어요': 21}


In [16]:
x=token.texts_to_sequences(docs)
print('리뷰 텍스트, 토큰화 결과:',x)

리뷰 텍스트, 토큰화 결과: [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


In [17]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

padded_x=pad_sequences(x, 4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [18]:
word_size=len(token.word_index) +1
model=Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()
              

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              176       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 209
Trainable params: 209
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 824ms/step - loss: 0.7025 - accuracy: 0.3000
Epoch 2/20
1/1 [==============================] - 0s 3ms/step - loss: 0.7002 - accuracy: 0.3000
Epoch 3/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6978 - accuracy: 0.3000
Epoch 4/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6955 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6932 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6908 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6885 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6862 - accuracy: 0.6000
Epoch 9/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6839 - accuracy: 0.6000
Epoch 10/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6817 - accuracy: 0.7000
Epoch 11/20
1/1 [====================

In [22]:
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

1/1 [==============================] - 0s 72ms/step - loss: 0.6566 - accuracy: 0.9000

 Accuracy: 0.9000
